name: bitcoin_mining_env
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.9.13
  - pandas
  - matplotlib
  - numpy
  - geopandas
  - pip:
    - ipykernel==6.29.5
    - openpyxl==3.1.5
